<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfFadlh\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfFadlh/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQfFadlh.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQfFadlh\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQfFadlh\App_KernelProdContainer([
    'container.build_hash' => 'QfFadlh',
    'container.build_id' => 'ae479d81',
    'container.build_time' => 1645794825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfFadlh');
