<?php

namespace ContainerQfFadlh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBattleTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\BattleType' shared autowired service.
     *
     * @return \App\Form\BattleType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BattleType'] = new \App\Form\BattleType();
    }
}
