<?php

namespace ContainerKPvezXl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBattleRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BattleRepository' shared autowired service.
     *
     * @return \App\Repository\BattleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BattleRepository'] = new \App\Repository\BattleRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
