<?php

namespace ContainerHUHC5KV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBattleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..RsvknS.App\Entity\Battle' shared service.
     *
     * @return \App\Entity\Battle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..RsvknS": it references class "App\\Entity\\Battle" but no such service exists.');
    }
}
