<?php

namespace ContainerErW0h9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__RsvknSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..RsvknS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..RsvknS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'battle' => ['privates', '.errored..service_locator..RsvknS.App\\Entity\\Battle', NULL, 'Cannot autowire service ".service_locator..RsvknS": it references class "App\\Entity\\Battle" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'battle' => 'App\\Entity\\Battle',
            'entityManager' => '?',
        ]);
    }
}
