<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErW0h9T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErW0h9T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErW0h9T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErW0h9T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErW0h9T\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErW0h9T',
    'container.build_id' => 'baf20669',
    'container.build_time' => 1645785426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErW0h9T');
