<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHUHC5KV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHUHC5KV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHUHC5KV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHUHC5KV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHUHC5KV\App_KernelDevDebugContainer([
    'container.build_hash' => 'HUHC5KV',
    'container.build_id' => '46a954c2',
    'container.build_time' => 1646153451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHUHC5KV');
