<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7TV2DC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7TV2DC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7TV2DC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7TV2DC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB7TV2DC\App_KernelDevDebugContainer([
    'container.build_hash' => 'B7TV2DC',
    'container.build_id' => '61bb0d8e',
    'container.build_time' => 1646217779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB7TV2DC');
